<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon />
    <AssemblyTitle>Barcode Label Printing</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BarcodePrinter.Client.Core\BarcodePrinter.Client.Core.csproj" />
    <ProjectReference Include="..\BarcodePrinter.Printing.Client\BarcodePrinter.Printing.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>
</Project>
