<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BarcodePrinter.Domain\BarcodePrinter.Domain.csproj" />
    <ProjectReference Include="..\..\shared\BarcodePrinter.Contracts\BarcodePrinter.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
</Project>
